version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor   # Configures Airflow to use the LocalExecutor (runs tasks as separate subprocesses on the same machine).
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__WEBSERVER__SECRET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
  volumes:
    - ./data:/opt/airflow/data:rw
    - ./pipelines:/opt/airflow/pipelines
    - ./dags:/opt/airflow/dags
    - ./requirements.txt:/requirements.txt
  networks:
    - airflow-network
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-network
    restart: always

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always
    depends_on:
      init:
        condition: service_completed_successfully

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      init:
        condition: service_completed_successfully

  init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username airflow --firstname admin --lastname admin --role Admin --email admin@example.com --password airflow
      "
    restart: "no"

volumes:
  postgres-db-volume:

networks:
  airflow-network:
    driver: bridge
